//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCobros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cartera()
        {
            this.Pago = new HashSet<Pago>();
            this.Gestion = new HashSet<Gestion>();
        }
    
        public int id_cartera { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
        public decimal saldo { get; set; }
        public int id_factura { get; set; }
        public int id_usuario { get; set; }
        public int id_estado { get; set; }
        public Nullable<int> id_mora { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Factura_Credito Factura_Credito { get; set; }
        public virtual Mora Mora { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gestion> Gestion { get; set; }
    }
}
