//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCobros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente_Tipo_Pago
    {
        public int id_cliente_tipo_pago { get; set; }
        public string no_tarjeta { get; set; }
        public string fecha_vencimiento { get; set; }
        public string cvv { get; set; }
        public int id_cliente { get; set; }
        public int id_estado { get; set; }
    
        public virtual Ciente Ciente { get; set; }
    }
}
