//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCobros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gestion()
        {
            this.Detalle_Gestion = new HashSet<Detalle_Gestion>();
        }
    
        public int id_gestion { get; set; }
        public int id_usuario { get; set; }
        public int id_cartera { get; set; }
    
        public virtual Cartera Cartera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Gestion> Detalle_Gestion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
