//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCobros.Models.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int id_bitacora { get; set; }
        public string accion { get; set; }
        public string usuario { get; set; }
        public string cliente { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
    }
}
