//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCobros.Models.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura_Credito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura_Credito()
        {
            this.Cartera = new HashSet<Cartera>();
        }
    
        public int id_factura { get; set; }
        public decimal total { get; set; }
        public int cantidad_cuotas { get; set; }
        public decimal monto_cuota { get; set; }
        public int id_cliente { get; set; }
        public int dia_mes_pago { get; set; }
        public string estado { get; set; }
        public string serie { get; set; }
        public string numero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cartera> Cartera { get; set; }
        public virtual Ciente Ciente { get; set; }
    }
}
